### ISSUE TITLE
This is a breaking change for mongoid based rails apps

### ISSUE THREAD

**Issue by prcongithub** [CanCanCommunity/cancancan#680]
https://github.com/CanCanCommunity/cancancan/blob/f0fbe69249d2e8242c060ce495353b0799472eb7/lib/cancan/ability.rb#L305

**Comment by Liberatys** [comment]
@prcongithub hasn't this been addressed in #673

**Comment by prcongithub** [comment]
My bad, since a new tag is not pushed, I thought it's not fixed yet.
